#if !defined (DECLARE_PARSER_TABLE)

#define DECLARE_PARSER_TABLE()	static parser_code	sm_mapCode[]

#define IMPLEMENT_PARSER_TABLE( _parser_name_ )	\
_parser_name_::parser_code _parser_name_::sm_mapCode[] = \
{\
	et_nonprint_char,\
	et_nonprint_char,\
	et_nonprint_char,\
	et_nonprint_char,\
	et_nonprint_char,\
	et_nonprint_char,\
	et_nonprint_char,\
	et_nonprint_char,\
	et_nonprint_char,\
	et_nonprint_char,\
	et_lf_endl,\
	et_nonprint_char,\
	et_nonprint_char,\
	et_cr_endl,\
	et_nonprint_char,\
	et_nonprint_char,\
	et_nonprint_char,\
	et_nonprint_char,\
	et_nonprint_char,\
	et_nonprint_char,\
	et_nonprint_char,\
	et_nonprint_char,\
	et_nonprint_char,\
	et_nonprint_char,\
	et_nonprint_char,\
	et_nonprint_char,\
	et_nonprint_char,\
	et_nonprint_char,\
	et_nonprint_char,\
	et_nonprint_char,\
	et_nonprint_char,\
	et_nonprint_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_value_delim,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_key_name_delim_start,\
	et_print_char,\
	et_key_name_delim_end,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_print_char,\
	et_nonprint_char,\
};

#endif	//	!defined(DECLARE_PARSER_TABLE)

